title: "Sérgio Rebelo"
description: "Engineering Leader & Hands-On Developer | Entrepreneur"
url: ""          # e.g., https://sergiorebelo.github.io
baseurl: ""      # keep empty for user site
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
theme: null

lang_default: en
langs:
  - code: en
    label: English
    path: /
  - code: pt
    label: Português
    path: /pt